# fly.toml file generated for lumoslavabot on 2021-10-27T20:08:02+03:00

app = "lumoslavabot"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true